name: Test

on:
  - pull_request

env:
  DEFAULT_PYTHON: 3.7

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: "Test: Info"
        run: ./plextraktsync.sh info

# vim:ts=2:sw=2:et
